### ISSUE TITLE
what is the small circle in the kabat numbering?

### ISSUE THREAD

**Issue by ppxwwtaking** [prihoda/AbNumber#20]
I print the chain numbering using kabat scheme. It shows some small circles under some residues. This never happens on other schemes. Could you explain what means?

**Comment by prihoda** [comment]
It shows "Vernier" positions - residues in proximity to CDRs, as defined in this paper:

> Foote, J., & Winter, G. (1992). Antibody framework residues affecting the
conformation of the hypervariable loops. Journal of Molecular Biology,
224(2), 487–499. https://doi.org/10.1016/0022-2836(92)91010-M

They are defined based on these Kabat positions: https://github.com/prihoda/AbNumber/blob/a8c1bbae9aea78974e84b59c08d15a70304946a1/abnumber/common.py#L119-L133
